listeners:
  - address: 0.0.0.0:8001
    cluster: proxy
    tls: server_ssl
clusters:
  - name: proxy
    endpoints:
    - 127.0.0.1:8080
tls:
  - name: client_ssl
    key: ./crt/client.pem
    cert: ./crt/client.crt
  - name: server_ssl
    key: ./crt/server.pem
    cert: ./crt/server.crt