listeners:
  - address: 0.0.0.0:8000
    cluster: proxy
clusters:
  - name: proxy
    endpoints:
    - 127.0.0.1:8001
    tls: client_ssl
tls:
  - name: client_ssl
    key: ./crt/client.pem
    cert: ./crt/client.crt
  - name: server_ssl
    key: ./crt/server.pem
    cert: ./crt/server.crt