listeners:
  - address: 0.0.0.0:8002
    cluster: proxy
    tls: server_ssl
clusters:
  - name: proxy
    endpoints:
    - 127.0.0.1:8003
tls:
  - name: client_ssl
    ca: ./crt/ca.crt
    key: ./crt/client.pem
    cert: ./crt/client.crt
  - name: server_ssl
    ca: crt/ca.crt
    key: ./crt/server.pem
    cert: ./crt/server.crt